# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = ["nvme" "xhci_pci" "ahci" "usb_storage" "usbhid" "sd_mod"];
  boot.initrd.kernelModules = [];
  boot.kernelModules = ["kvm-amd"];
  boot.extraModulePackages = [];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/c94d7fef-f10a-4070-b8bc-4beaf45d3a47";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/DD60-1132";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/e5bd98a0-8c1a-4edd-9d1a-42a857fa7419"; }
    ];

  # Automount game drive
  fileSystems."/run/media/xllvr/Games" = {
    device = "/dev/disk/by-uuid/32e168a3-3ef4-4a95-83e0-a95a6f15617b";
  };

  # Automount media
  fileSystems."/run/media/xllvr/Media" = {
    device = "/dev/disk/by-uuid/f59d9bbb-5513-46ca-9051-ba7214900e12";
  };

  # Automount storage
  fileSystems."/run/media/xllvr/Storage" = {
    device = "/dev/disk/by-uuid/3fb9f454-d0fe-42ee-8fa1-3bd92ae7cdf0";
  };

  # Packages for keyboards
  services.udev.packages = with pkgs; [
    qmk
    qmk-udev-rules
    qmk_hid
    # via
    vial
  ];

  # Mouse setup for Elecom Huge
  services.udev.extraHwdb = ''
    evdev:input:b*v056Ep010C*
     KEYBOARD_KEY_90008=btn_middle
     KEYBOARD_KEY_90005=btn_side
     KEYBOARD_KEY_90004=btn_extra
  '';

  # Enable printing
  services.printing = {
    enable = true;
    drivers = [pkgs.hplip pkgs.gutenprint];
  };
  services.avahi = {
    enable = true;
    nssmdns4 = true;
    openFirewall = true;
  };

  # Enable bluetooth
  hardware.bluetooth.enable = true;
  hardware.bluetooth.powerOnBoot = true;
  services.blueman.enable = true;

  # Enable sound with pipewire.
  services.pulseaudio.enable = false;
  security.rtkit.enable = true;
  services.pipewire = {
    enable = true;
    alsa.enable = true;
    alsa.support32Bit = true;
    pulse.enable = true;
    extraConfig.pipewire.adjust-sample-rate = {
      "context.properties" = {
        "default.clock.allowed-rates" = [32000 44100 48000 88200 96000 192000];
      };
    };
  };

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  networking.useDHCP = lib.mkDefault true;

  # Enable openGL
  hardware.graphics.enable = true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
